### ISSUE TITLE
Cambiar el color del combat tracker + Contador de PV que descienda, no que suba

### ISSUE THREAD

**Issue by vinsel95** [elfonochasis/Sistema-Hitos-Foundry-VTT#11]
¡Hola!

Lo primero, muchas gracias, este sistema me gusta muchísimo, y usándolo con Foundry me está solucionando muchísimo la vida :)

Bueno, al tema, 

Lo primero, me gustaría saber cómo poder cambiar el color del combat tracker, ya que el color de base que trae el sistema se hace un poco engorroso el poder seguir y ver todos los datos fácilmente
![unknown](https://user-images.githubusercontent.com/82233853/114222417-dbeb1100-996e-11eb-9912-b3f118fdc5dd.png)

Y lo segundo, el contador de PV o PG que descienda, no que aumente, me explico con un ejemplo visual:
![Captura](https://user-images.githubusercontent.com/82233853/114222764-41d79880-996f-11eb-8862-95bba4d1c565.PNG)
A la izquierda el PJ está moribundo, mientras que a la derecha el personaje está totalemente sano; sé que es algo meramente decorativo, pero resulta más cómo que la barra de PG/PV vaya en descenso, no en aumento
 
Estas dos cosas que te comento son meramente visuales, y tampoco hay una "gran necesidad de ello", y lo comentado anteriormente, muchísimas gracias por todo!

Buen día! ^^

**Comment by LotsOfLore** [comment]
Yo también me sumo a este issue, sobretodo los colores del combat tracker! 
Muchas gracias por vuestro trabajo!

**Comment by elfonochasis** [comment]
En la rama DEV deberían estar corregidos ambos problemas.
Disculpad por el retraso en la respuesta!

**Comment by elfonochasis** [comment]
![imagen](https://user-images.githubusercontent.com/13823829/124949718-1cac0200-e012-11eb-91fd-aa5c980fa0bb.png)
![imagen](https://user-images.githubusercontent.com/13823829/124949789-29c8f100-e012-11eb-9ae8-0ab7b3bdb3a6.png)
