### ISSUE TITLE
compatibilidad 0.8.6 (atributos y habilidades)

### ISSUE THREAD

**Issue by Pluvium** [elfonochasis/Sistema-Hitos-Foundry-VTT#13]
No aparecen y no se pueden editar  atributos ni habilidades. ¿puede que sea por la última actualización de Foundry a 0.8.6?
Gracias

**Comment by LotsOfLore** [comment]
Confirmo que parece no funcionar con la nueva versión de Foundry. Espero que se pueda actualizar, muchas gracias :)

**Comment by elfonochasis** [comment]
Hay una versión de prueba en la rama DEV si queréis ir probando.
https://raw.githubusercontent.com/elfonochasis/Sistema-Hitos-Foundry-VTT/dev/system.json

**Comment by Pluvium** [comment]
Muchísimas gracias por tu esfuerzo

**Comment by LotsOfLore** [comment]
Qué maravilla, muchísimas gracias!
