### ISSUE TITLE
No aperecen los dados cuando usas cualquier habilidad de la hoja PJ para hacer una tirada

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#19]
Version Foundry 0.8.8
Versión Hitos: 0.9.3
Chrome actualizado en Windows 10 / Foundry VTT en Raspberry Pi 4 (Raspbian Buster)
Modulo Dice So Nice + Dice Tray activados y funcionantes. 

Al hacer click sobre una de las habilidades de la hoja de un PJ, la tirada sale correcta en chat, pero no se mostran los dados. Sin embargo sí que aparecen haciendo una tirada cualquiera sin pasar por la hoja, o utilizando el dice tray. 

![Clipboard02](https://user-images.githubusercontent.com/76159017/125585843-461f2a4d-79f5-4970-b91c-01efb5c991ff.jpg)

Gracias por la atención y por tu trabajo!

**Comment by elfonochasis** [comment]
Ya está subida una versión compatible con el módulo!
Muchas gracias 
![imagen](https://user-images.githubusercontent.com/13823829/125589566-14809683-85ef-4d44-a6cd-f9fd2e51ccfe.png)
