### ISSUE TITLE
Todos los campos en la hoja PJ y el campo "Motivación" y "Concepto" en las hoja de Organización no funcionan correctamente

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#23]
FoundryVTT version: 0.8.9
Hitos version: 0.9.5 
Browser: Microsoft Edge / Google Chrome latest versions.

ISSUE
Los campos de la hoja PJ no aceptan escribir letras "s", si tecleas esa letra simplemente no aparece. 
Los campos "Concepto" y "Motivación" en la hoja de Organización tampoco permite escribir letras "s". Además, cualquier cosa escribas en este campo no queda grabado, es decir, al cerrar la hoja y volver a reabrirla el campo vuelve en blanco. 

Gracias por la atención :)

**Comment by elfonochasis** [comment]
Buenas,
Tomo nota y reviso lo que comentas.
Muchas gracias!

**Comment by elfonochasis** [comment]
Debería quedar corregido en la v0.9.6
![imagen](https://user-images.githubusercontent.com/13823829/143861660-e92f2a67-8088-40e4-9032-7aee9f95ae29.png)

**Comment by LotsOfLore** [comment]
Hola, desgraciadamente por mi parte el problema sigue igual. He grabado un videoclip para enseñar como se ve de mi parte, en el video creo hojas e intento escribir "asd" en todas partes. Algunos muy pocos campos funcionas, la mayoría no. Es decir solo la S mayuscula se puede escribir: 

https://user-images.githubusercontent.com/76159017/145088521-ed20cbfc-f071-4f04-84bf-a023ec5523a3.mp4

Gracias por tu atención

**Comment by elfonochasis** [comment]
Buenas!
Estoy probando ahora mismo y me deja. Qué extraño... Si activas la consola con F12, ¿te sale algún error? ¿Qué módulos tienes activos?
Un saludo
![imagen](https://user-images.githubusercontent.com/13823829/145091207-f6f35b95-da06-4859-ae93-2a4882b2f920.png)

**Comment by LotsOfLore** [comment]
Lo he abierto en Chrome (lo tenía en windows standalone, pero en browser pasa lo mismo) y he quitado todos los modulos y vuelto a activar cada uno hasta encontrar si se producía el error, y sí lo he encontrado, creo. 
Al activar el modulo: "Library: DF Hotkeys" (https://foundryvtt.com/packages/lib-df-hotkeys) se produce el error, evidentemente hay un conflicto ahí! He grabado la consola pero no se si tiene algo útil que mostrar. Sin embargo, desactivando ese modulo las hojas funcionan perfectamente. 

https://user-images.githubusercontent.com/76159017/145097763-c7fc9df2-7683-433c-aea0-2de36312faf6.mp4
(no creo haya nada útil que ver ahí, no se por que no soy programador lo siento, pero mensajes de "error" no salían...

**Comment by elfonochasis** [comment]
¡Cazado! Vale, no he visto nada a primera vista y voy a tener que darle una vuelta. Mientras tanto si en la configuración cambias la tecla que viene por defecto que es la s por = o alguna de esas, no debería darte problemas!
