### ISSUE TITLE
El Combat Tracker sigue teniendo una imagen de background blanca. No se lee en modalidad ventana separada.

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#24]
FoundryVTT version: 0.8.9
Hitos version: 0.9.5
Browser: Microsoft Edge / Google Chrome latest versions. 

El Combat Tracker una vez descorporado (click derecho sobre el icono), vuelve a tener una imagen de background blanca que no permite leer bien el contenido (ver imagen). 

![Combat Tracker Screenshot](https://user-images.githubusercontent.com/76159017/136182449-c09be5c5-2f1f-46d2-ba18-efe97c18e4da.jpg)

Gracias por la atención :)

**Comment by elfonochasis** [comment]
Buenas,
Lo reviso y hago corrección.
Gracias!

**Comment by elfonochasis** [comment]
Debería quedar corregido en la v0.9.6
![Uploading imagen.png…]()
