### ISSUE TITLE
Las armas no funcionan, las armaduras no aplican reducción al daño

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#26]
Usando la v9, en Chrome, con 0 modulos activos. 

Intenté crear un arma y darla a un PJ. Al hacer click en el arma de la hoja PJ no sale la tirada de ataque. 
Además, equipar un objeto armadura con un valor de reducción al daño, no aplica la reducción al personaje. 
Video aquí:

https://user-images.githubusercontent.com/76159017/149790278-1c77eb71-f9e3-4925-9581-1f3ed9e1aa2c.mp4

**Comment by elfonochasis** [comment]
Buenas!
Estás usando la versión 0.9.7 de Hitos?
Acabo de probar y a mi si me realiza la tirada de ataque. La RD tengo que revisar que está pasando

**Comment by LotsOfLore** [comment]
Sí, la actualice a la 0.9.7 de Hitos y la probé. 
También he probado esta nueva versión con la versión anterior de Foundry, y pasa lo mismo. Al cliquear no hace nada

**Comment by elfonochasis** [comment]
¿Podrías grabar el mismo vídeo pero habiendo pulsado F12 para ver que error o mensaje salta en la consola?
¡Muchas gracias!

**Comment by LotsOfLore** [comment]
Aquí lo tienes :) 
Aparece un error 

https://user-images.githubusercontent.com/76159017/149798517-eb4ee718-29c4-48ce-8e3c-a9ee43e132fa.mp4

**Comment by LotsOfLore** [comment]
También un screenshot al punto del error, maybe? 
![image](https://user-images.githubusercontent.com/76159017/149798946-f4c7ccfb-83d7-4fd3-b85e-f17863c720a2.png)

**Comment by elfonochasis** [comment]
Ya se por donde van los tiros! En cuánto tenga un rato, lo corrijo y hago actualización!
De nuevo, mil gracias por el feedback!

**Comment by elfonochasis** [comment]
He subido una nueva versión que debería de funcionar.
Perdona que con las nuevas versiones que van saliendo, se van rompiendo cosas :(

**Comment by LotsOfLore** [comment]
Qué rápido! 
Muchas gracias! :)
