### ISSUE TITLE
Los campos de texto la hoja PJ no aceptan escritura

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#27]
Nuevos problemas, ¡lo siento! 
Al poner el cursor en los campos de texto de las hojas PJ/Organización etc. y teclear algo, en vez de escrivir el programa pasa los atajos genericos como si no estuvieras dentro de un campo de escritura. Por ejemplo, a excepción de los dos campos extra en la hoja PJ (ver vídeo), los cuales sí funcionan correctamente, en los demás campos si intentas escribir "wasd" en vez de aparecer las letras se mueve un token, si es seleccionado, o al presionar spacebar para introducir un espacio en el texto en vez de escribir se pone el juego en pausa... 

https://user-images.githubusercontent.com/76159017/150121397-1d11655d-2d24-40f5-beb6-2454628a903c.mp4

**Comment by elfonochasis** [comment]
Buenas!
Lo reviso en cuanto pueda. A ver que está pasando y te comento

**Comment by elfonochasis** [comment]
He visto que si borras en la configuración, el mapeo de las teclas, funciona correctamente. Voy a ver como evitar que pase eso sin tener que borrar la config desde ahí.
¡Seguiré informando!

**Comment by elfonochasis** [comment]
Tras investigar y comentarlo por el Discord oficial de Foundry, hay más gente con el mismo problema debido a un fallo en Foundry. https://gitlab.com/foundrynet/foundryvtt/-/issues/6509
A ver si lo corrigen y se solventa. Mientras tanto, desde la configuración deshabilita las letras y el espacio si puedes en la configuración de teclado. Otra opción es que copies y pegues en el campo.
Disculpa las molestias y a ver si le dan solución rápido!

**Comment by LotsOfLore** [comment]
Anda mira! Vale, gracias por las info :)

**Comment by elfonochasis** [comment]
Buenas!
He subido una versión que debería evitar el problema mientras se corrige en el core de Foundry.
Un saludo!
