### ISSUE TITLE
Visualization bug on the character sheets' layout

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#5]
Hi, first of all enhorabuena! Thank you for working on bringing Hitos into FoundryVTT, much appreciated!!
Just testing it out I can see that there is the word "hitos." displayed together with every parameter element of the sheet. As if the label wasn't properly set for these elements (see screenshot). 

Thank you and keep up the good work!
![Hitos_captura](https://user-images.githubusercontent.com/76159017/107879494-5ea8a000-6ed9-11eb-8cb4-8200a2c44537.jpg)

**Comment by elfonochasis** [comment]
Hi LotsOfLore! Thanks for your kind words!
Hitos system is only available in Spanish nowadays. I can add a en.json with every tag in spanish so they will appear correctly.

Greetings

**Comment by LotsOfLore** [comment]
Got it thank you.
