### ISSUE TITLE
la escritura se va

### ISSUE THREAD

**Issue by ENELKO** [elfonochasis/Sistema-Hitos-Foundry-VTT#6]
![Captura de pantalla 2021-02-23 190357](https://user-images.githubusercontent.com/78974852/108887334-68818000-760a-11eb-9145-ea60f0fb2729.png)

Pasa lo mismo en Atletismo en la hora de PJ

**Comment by LotsOfLore** [comment]
Confirmo este bug. Parece que después de haber escrito algo en el campo de las notas en la hoja de organizaciones, y de haberla cerrada, al reabrir la hoja el texto se muestra con el código de formatación visible, en vez de aplicado al texto.

**Comment by elfonochasis** [comment]
Debería estar corregido en la versión 0.9.1 que ya está publicada!
