### ISSUE TITLE
Hoja PJ: campos vacíos, no se pueden editar. 

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#8]
Hola, 
he notado que los campos de "ARMAS", "ARMADURAS" y "INVENTARIO" en la hoja PJ no parecen activados. Es decir no existe control para editarlos y introducir texto alcuno. No se si esto es un error, o simplemente no han sido implementados todavía. 

![Armas_Armaduras](https://user-images.githubusercontent.com/76159017/110508889-ce3d3400-8101-11eb-8e21-005f11a4bbe7.jpg)
![Inventario](https://user-images.githubusercontent.com/76159017/110508904-d301e800-8101-11eb-9129-27d252548203.jpg)

**Comment by elfonochasis** [comment]
En el inventario, armas y armaduras tienes que crear los objetos (items) y los arrastras a la ficha para que se añadan!

**Comment by LotsOfLore** [comment]
Aja! Fantastico lo probaré entonces!
