### ISSUE TITLE
Sería posible modificar el valor MAX de Drama? (Hoja PJ)

### ISSUE THREAD

**Issue by LotsOfLore** [elfonochasis/Sistema-Hitos-Foundry-VTT#9]
Hola, 
en Hitos el avanzamiento de los personajes se puede hacer bajando el valor máximo de Puntos de Drama para comprar puntos de habilidades y caracteristicas. Actualmente no parece posibil editar el valor máximo de Drama. 
Gracias por la atención! 
![Modificar Drama](https://user-images.githubusercontent.com/76159017/110509358-4efc3000-8102-11eb-9285-0695a55e08dd.jpg)

**Comment by elfonochasis** [comment]
Lo marco como mejora para añadirlo en la próxima actualización!

**Comment by elfonochasis** [comment]
![imagen](https://user-images.githubusercontent.com/13823829/124953376-621dfe80-e015-11eb-8770-e2c5bcc51cfe.png)
